config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "static_pages#index"
  resources :users, only: [:index, :destroy]
  resources :movies do
    resources :reviews, only: [:create, :update, :edit, :destroy] do
      resource :votes, only: [:create]
    end
  end

  namespace :api do
    namespace :v1 do
      resources :reviews, only: [:index] do
        resources :votes, only: [:create]
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Movie Review Site</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1><%= link_to "38 Stahs", root_path %></h1>
        </li>
      </ul>

      <section class="top-bar-section">
        <!-- Right Nav Section -->
        <ul class="right">
          <% if user_signed_in? %>
            <li class="active"><%= link_to "Add Movie", new_movie_path %></li>
            <li><%= link_to "Welcome #{current_user.username}!", root_path %></li>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <% unless current_user.profile_photo.file.nil? %>
            <div id="profile-photo-container">
              <li id="profile-photo"><%= image_tag current_user.profile_photo.url, { size: "45x45" } %></li>
            </div>
            <% end %>
          <% else %>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <li><%= link_to 'Sign In', new_user_session_path %></li>
          <% end %>
        </ul>

        <!-- Left Nav Section -->
        <ul class="left">
          <li><%= link_to "Movies", movies_path %></li>
          <% if user_signed_in? && current_user.admin? %>
            <li><%= link_to "All Users", users_path %></li>
          <% end %>
        </ul>
      </section>
    </nav>

    <div class="flash-notices">
      <% flash.each do |type, message| %>
        <div class="flash-<%= type %>">
          <%= message %>
        </div>
      <% end %>
    </div>

    <div class="row">
      <div class="small-12 columns">
        <%= yield %>
      </div>
    </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>